# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: SOPSy
site_description: SOPS Python wrapper library
site_url: https://sopsy.nikaro.net
repo_url: https://github.com/nikaro/sopsy
repo_name: nikaro/sopsy
watch:
  - ./mkdocs.yml
  - ./src/sopsy/
  - ./htmlcov

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Usage: index.md
  - reference.md
  - changelog.md
  - coverage.md

plugins:
  - search
  - coverage
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/autorefs/objects.inv
            - https://www.mkdocs.org/objects.inv
            - https://python-markdown.github.io/objects.inv
          paths: [src]
          options:
            docstring_options:
              ignore_init_summary: true
            filters: ["!^_"]
            inherited_members: true
            line_length: 80
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: [!relative $config_dir]
      check_paths: true
